# Generated by Django 2.2.24 on 2021-11-28 15:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [("authnapp", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="shopuser",
            name="activation_key_expires",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 11, 30, 15, 23, 59, 670839, tzinfo=utc),
                verbose_name="актуальность ключа",
            ),
        )
    ]
